package net.balamah.voiddim.entity.client;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class CorruptedWarriorAnimations {
	public static final Animation IDLE = Animation.Builder.create(0f).build();
	public static final Animation WALK = Animation.Builder.create(0.79167f).looping()
	.addBoneAnimation("left_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(-42f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(42f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(-42f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(-42f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(42f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(-42f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(42f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(-42f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(42f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(42f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(-42f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.75f, AnimationHelper.createRotationalVector(42f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("cape",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(35f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final Animation STRONG_ATTACK = Animation.Builder.create(0.625f)
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.TRANSLATE, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.29167f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.45833f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("arms",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(-42.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.45833f, AnimationHelper.createRotationalVector(77.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("arms",
		new Transformation(Transformation.Targets.SCALE,
			new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createScalingVector(1f, 1f, 1.3f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-93.86f, -29.72f, -4.31f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("sword",
		new Transformation(Transformation.Targets.TRANSLATE, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(3f, -2f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.45833f, AnimationHelper.createTranslationalVector(3f, -5f, -1f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("sword",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(17.5f, 2.49f, 25.22f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.45833f, AnimationHelper.createRotationalVector(22.16f, 37.12f, 38.24f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-95.92f, 32.36f, -3.18f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(-27.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.TRANSLATE, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(0f, -2f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-40f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_calf",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(40f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_calf",
		new Transformation(Transformation.Targets.SCALE,
			new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createScalingVector(1f, 1.5f, 1f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_leg",
		new Transformation(Transformation.Targets.TRANSLATE, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.125f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_calf",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(42.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final Animation STRONGEST_ATTACK = Animation.Builder.create(1f)
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.TRANSLATE, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.29167f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.54167f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.625f, AnimationHelper.createRotationalVector(45f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("arms",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(-80f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.54167f, AnimationHelper.createRotationalVector(-77.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.625f, AnimationHelper.createRotationalVector(77.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("arms",
		new Transformation(Transformation.Targets.SCALE,
			new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1.3f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-93.86f, -29.72f, -4.31f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(-32.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("sword",
		new Transformation(Transformation.Targets.TRANSLATE, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(3f, -2f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("sword",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(18.02f, 13.58f, 28.8f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-95.92f, 32.36f, -3.18f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(-27.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.TRANSLATE, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(0f, -2f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-40f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_calf",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(40f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_calf",
		new Transformation(Transformation.Targets.SCALE,
			new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1.5f, 1f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_leg",
		new Transformation(Transformation.Targets.TRANSLATE, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.125f, AnimationHelper.createTranslationalVector(0f, -3f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_calf",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(42.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final Animation SUMMON_PROJECTILE = Animation.Builder.create(0.5f)
	.addBoneAnimation("head",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(-25.77f, 13.73f, -6.06f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-127.07f, 8.53f, 0.69f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(19.92f, 1.3f, -7.39f),
				Transformation.Interpolations.LINEAR))).build();
	public static final Animation SPECIAL_ATTACK = Animation.Builder.create(0.79167f)
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("cape",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(1f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("arms",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(-75f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-22.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(-25.02f, -22.48f, -17.4f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("sword",
		new Transformation(Transformation.Targets.TRANSLATE, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(-1.75f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.125f, AnimationHelper.createTranslationalVector(1.25f, -2f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("sword",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(-180f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(-179.74f, 1.98f, -62.5f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(-202.24f, 1.98f, -62.5f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-162.24f, 1.98f, -62.5f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(-25.02f, 22.48f, 17.4f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-30f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final Animation NORMAL_ATTACK_1 = Animation.Builder.create(0.41667f)
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, -22.5f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_arm",
		new Transformation(Transformation.Targets.TRANSLATE, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.08333f, AnimationHelper.createTranslationalVector(0f, -4f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.20833f, AnimationHelper.createRotationalVector(-116.03f, -31.37f, 59.15f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(48.97f, -31.37f, 59.15f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(-35f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(-42.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("sword",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 32.5f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final Animation NORMAL_ATTACK_2 = Animation.Builder.create(0.33333f)
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(0f, 27.5f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(0f, -27.5f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("cape",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-132.43f, 31.77f, -25.7f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(-143.31f, 14.72f, -66.46f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-40.81f, 14.72f, -66.46f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-55f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("sword",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.04167f, AnimationHelper.createRotationalVector(0f, 27.5f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(0f, 45f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final Animation NORMAL_ATTACK_3 = Animation.Builder.create(0.375f)
	.addBoneAnimation("right_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.04167f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-36.29f, 14.26f, -10.25f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(-53.79f, 14.26f, -10.25f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.20834334f, AnimationHelper.createRotationalVector(-61.29f, 14.26f, -10.25f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(-50.43f, 4.75f, -3.42f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.04167f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(12.32f, 2.15f, -9.77f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.04167f, AnimationHelper.createRotationalVector(12.79f, -12.2f, -2.75f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(27.13f, -25.42f, -8.11f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(33.75f, -21.7f, -6.02f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(41.25f, -21.7f, -6.02f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-22.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(-21.25f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_calf",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(17.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(17.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_calf",
		new Transformation(Transformation.Targets.SCALE,
			new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createScalingVector(1f, 1.2f, 1f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.2916767f, AnimationHelper.createScalingVector(1f, 1.2f, 1f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.3433333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.04167f, AnimationHelper.createRotationalVector(27.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(28.93f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_leg",
		new Transformation(Transformation.Targets.SCALE,
			new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.04167f, AnimationHelper.createScalingVector(1f, 1.2f, 1f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.2916767f, AnimationHelper.createScalingVector(1f, 1.2f, 1f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.3433333f, AnimationHelper.createScalingVector(1f, 1f, 1f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("sword",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(0f, 17.5f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_decoration",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.04167f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(40f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("cape",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(-40f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
}
