package net.balamah.voiddim.entity.client;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class WerewolfAnimations {
	public static final Animation IDLE = Animation.Builder.create(0f).build();
	public static final Animation ATTACK_BITE = Animation.Builder.create(0.375f)
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("jaw",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.20833f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("upper_mouth",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.20833f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_shoulder_bicep",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_shoulder_bicep",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final Animation ATTACK_HIT = Animation.Builder.create(0.5834334f)
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.4167667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("front_paws",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(-155f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(-85f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.4167667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final Animation WALK = Animation.Builder.create(0.7083434f).looping()
	.addBoneAnimation("tail",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(35f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("back_paws",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(-27.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-37.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.54167f, AnimationHelper.createRotationalVector(-49.95f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.70833f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.2916767f, AnimationHelper.createRotationalVector(12.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.66667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_front_paw",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(-17.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(13.5f, 5.9f, 19.14f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.70833f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.70833f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_front_paw",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(-17.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(18.26f, -5.19f, -16.74f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.70833f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.70833f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
}
