package net.balamah.voiddim.entity.client;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class CorruptedWarriorAnimations {
	public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(0f).build();
	public static final AnimationDefinition WALK = AnimationDefinition.Builder.withLength(0.79167f).looping()
	.addAnimation("left_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(-42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.75f, KeyframeAnimations.degreeVec(-42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(-42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.75f, KeyframeAnimations.degreeVec(-42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.75f, KeyframeAnimations.degreeVec(42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.75f, KeyframeAnimations.degreeVec(42f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("cape",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition STRONG_ATTACK = AnimationDefinition.Builder.withLength(0.625f)
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.29167f, KeyframeAnimations.posVec(0f, -3f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.45833f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("arms",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.25f, KeyframeAnimations.degreeVec(-42.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.45833f, KeyframeAnimations.degreeVec(77.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("arms",
		new AnimationChannel(AnimationChannel.Targets.SCALE,
			new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.25f, KeyframeAnimations.scaleVec(1f, 1f, 1.3f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-93.86f, -29.72f, -4.31f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.25f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("sword",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.16667f, KeyframeAnimations.posVec(3f, -2f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.45833f, KeyframeAnimations.posVec(3f, -5f, -1f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("sword",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(17.5f, 2.49f, 25.22f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.45833f, KeyframeAnimations.degreeVec(22.16f, 37.12f, 38.24f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-95.92f, 32.36f, -3.18f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.25f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.16667f, KeyframeAnimations.posVec(0f, -2f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-40f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_calf",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(40f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_calf",
		new AnimationChannel(AnimationChannel.Targets.SCALE,
			new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.scaleVec(1f, 1.5f, 1f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_leg",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -3f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_calf",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(42.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition STRONGEST_ATTACK = AnimationDefinition.Builder.withLength(1f)
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.29167f, KeyframeAnimations.posVec(0f, -3f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.54167f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.625f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("arms",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-80f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.54167f, KeyframeAnimations.degreeVec(-77.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.625f, KeyframeAnimations.degreeVec(77.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("arms",
		new AnimationChannel(AnimationChannel.Targets.SCALE,
			new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1.3f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-93.86f, -29.72f, -4.31f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.25f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("sword",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(3f, -2f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("sword",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(18.02f, 13.58f, 28.8f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-95.92f, 32.36f, -3.18f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.16667f, KeyframeAnimations.posVec(0f, -2f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-40f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_calf",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(40f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_calf",
		new AnimationChannel(AnimationChannel.Targets.SCALE,
			new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1.5f, 1f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_leg",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -3f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_calf",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(42.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition SUMMON_PROJECTILE = AnimationDefinition.Builder.withLength(0.5f)
	.addAnimation("head",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(-25.77f, 13.73f, -6.06f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-127.07f, 8.53f, 0.69f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(19.92f, 1.3f, -7.39f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition SPECIAL_ATTACK = AnimationDefinition.Builder.withLength(0.79167f)
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("cape",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(1f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("arms",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-75f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(-25.02f, -22.48f, -17.4f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("sword",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(-1.75f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.125f, KeyframeAnimations.posVec(1.25f, -2f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("sword",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(-180f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(-179.74f, 1.98f, -62.5f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-202.24f, 1.98f, -62.5f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-162.24f, 1.98f, -62.5f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(-25.02f, 22.48f, 17.4f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition NORMAL_ATTACK_1 = AnimationDefinition.Builder.withLength(0.41667f)
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, -22.5f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.29167f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_arm",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.08333f, KeyframeAnimations.posVec(0f, -4f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.20833f, KeyframeAnimations.degreeVec(-116.03f, -31.37f, 59.15f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.29167f, KeyframeAnimations.degreeVec(48.97f, -31.37f, 59.15f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.25f, KeyframeAnimations.degreeVec(-42.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("sword",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 32.5f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition NORMAL_ATTACK_2 = AnimationDefinition.Builder.withLength(0.33333f)
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 27.5f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(0f, -27.5f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("cape",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-132.43f, 31.77f, -25.7f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(-143.31f, 14.72f, -66.46f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-40.81f, 14.72f, -66.46f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-55f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("sword",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.04167f, KeyframeAnimations.degreeVec(0f, 27.5f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(0f, 45f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition NORMAL_ATTACK_3 = AnimationDefinition.Builder.withLength(0.375f)
	.addAnimation("right_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.04167f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-36.29f, 14.26f, -10.25f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(-53.79f, 14.26f, -10.25f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-61.29f, 14.26f, -10.25f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-50.43f, 4.75f, -3.42f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.04167f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-12.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(12.32f, 2.15f, -9.77f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.04167f, KeyframeAnimations.degreeVec(12.79f, -12.2f, -2.75f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(27.13f, -25.42f, -8.11f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(33.75f, -21.7f, -6.02f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(41.25f, -21.7f, -6.02f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-21.25f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_calf",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_calf",
		new AnimationChannel(AnimationChannel.Targets.SCALE,
			new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1.2f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.2916767f, KeyframeAnimations.scaleVec(1f, 1.2f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.3433333f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.04167f, KeyframeAnimations.degreeVec(27.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(28.93f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_leg",
		new AnimationChannel(AnimationChannel.Targets.SCALE,
			new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.04167f, KeyframeAnimations.scaleVec(1f, 1.2f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.2916767f, KeyframeAnimations.scaleVec(1f, 1.2f, 1f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.3433333f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("sword",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(0f, 17.5f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("body_decoration",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.04167f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(40f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("cape",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.3433333f, KeyframeAnimations.degreeVec(-40f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
}
