package net.balamah.voiddim.entity.client;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class ShatteredSentinelMasterAnimations extends ShatteredSentinelAnimations {
	public static final AnimationDefinition SHATTER_GROUND_BEGIN = AnimationDefinition.Builder.withLength(0.6766666f)
	.addAnimation("head",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.375f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.54167f, KeyframeAnimations.degreeVec(37.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.625f, KeyframeAnimations.degreeVec(29.21f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.20833f, KeyframeAnimations.degreeVec(62.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.375f, KeyframeAnimations.degreeVec(80f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.58333f, KeyframeAnimations.degreeVec(92.47f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("arms",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("arms",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(-22.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.25f, KeyframeAnimations.degreeVec(-7.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-13.55f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.45833f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.58333f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(-57.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(-60f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -1.5f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.25f, KeyframeAnimations.degreeVec(32.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.29167f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-15f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.54167f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_calf",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.29167f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.54167f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition SHATTER_GROUND_PUSH = AnimationDefinition.Builder.withLength(0.5f)
	.addAnimation("head",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(40.92f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("arms",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.20834334f, KeyframeAnimations.posVec(0f, 0f, -2f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("arms",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-54.17f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-65f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-57.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0.20834334f, KeyframeAnimations.degreeVec(-60f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0.08343333f, KeyframeAnimations.posVec(0f, -1.5f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_calf",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition SHATTER_GROUND_END = AnimationDefinition.Builder.withLength(0.5f)
	.addAnimation("head",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(-21.58f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(109.97f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.29167f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("arms",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(-95f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(-57.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(-60f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, -1.5f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.08333f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(32.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_leg",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.25f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_calf",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(37.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("root",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition SHOCK_WAVE_INVOKE = AnimationDefinition.Builder.withLength(0.54167f)
	.addAnimation("arms",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.04167f, KeyframeAnimations.degreeVec(-70f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 0f, -32.5f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.45833f, KeyframeAnimations.degreeVec(0f, 0f, 27.5f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-57.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.45833f, KeyframeAnimations.degreeVec(-42.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 0f, 30f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.45833f, KeyframeAnimations.degreeVec(0f, 0f, -27.5f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-57.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.45833f, KeyframeAnimations.degreeVec(-42.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("stones",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition THROW_BLOCK = AnimationDefinition.Builder.withLength(0.83333f)
	.addAnimation("left_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_arm",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.29167f, KeyframeAnimations.degreeVec(-96.91f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-100f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.45833f, KeyframeAnimations.degreeVec(-107.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.5f, KeyframeAnimations.degreeVec(-90f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(-67.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-75f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.5f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(1.125f).looping()
	.addAnimation("stones",
		new AnimationChannel(AnimationChannel.Targets.POSITION, 
			new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(0.5f, KeyframeAnimations.posVec(0f, -1.17f, 0f),
				AnimationChannel.Interpolations.LINEAR), 
			new Keyframe(1.08333f, KeyframeAnimations.posVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
}
