package net.balamah.voiddim.entity.client;

import net.minecraft.client.render.entity.animation.*;

public class ShatteredSentinelMasterAnimations extends ShatteredSentinelAnimations {
	public static final AnimationDefinition SHATTER_GROUND_BEGIN = AnimationDefinition.Builder.create(0.6766666f)
	.addBoneAnimation("head",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.375f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.54167f, AnimationHelper.createRotationalVector(37.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.625f, AnimationHelper.createRotationalVector(29.21f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.20833f, AnimationHelper.createRotationalVector(62.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.375f, AnimationHelper.createRotationalVector(80f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.58333f, AnimationHelper.createRotationalVector(92.47f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("arms",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("arms",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-22.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(-13.55f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.45833f, AnimationHelper.createRotationalVector(-27.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.58333f, AnimationHelper.createRotationalVector(-35f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(-57.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(-60f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -1.5f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(32.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(-15f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(-25f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-15f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.54167f, AnimationHelper.createRotationalVector(-27.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_calf",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(20f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(25f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(15f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.54167f, AnimationHelper.createRotationalVector(25f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final AnimationDefinition SHATTER_GROUND_PUSH = AnimationDefinition.Builder.create(0.5f)
	.addBoneAnimation("head",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(40.92f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("arms",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0.20834334f, AnimationHelper.createTranslationalVector(0f, 0f, -2f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("arms",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(-35f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(-54.17f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.20834334f, AnimationHelper.createRotationalVector(-65f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0.20834334f, AnimationHelper.createRotationalVector(-57.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0.20834334f, AnimationHelper.createRotationalVector(-60f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0.08343333f, AnimationHelper.createTranslationalVector(0f, -1.5f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(-27.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_calf",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(25f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final AnimationDefinition SHATTER_GROUND_END = AnimationDefinition.Builder.create(0.5f)
	.addBoneAnimation("head",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(-21.58f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.125f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(109.97f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("arms",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(-95f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(-57.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(-60f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -1.5f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.08333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(32.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_leg",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(-37.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_calf",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(37.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("root",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final AnimationDefinition SHOCK_WAVE_INVOKE = AnimationDefinition.Builder.create(0.54167f)
	.addBoneAnimation("arms",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.04167f, AnimationHelper.createRotationalVector(-70f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, -32.5f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.45833f, AnimationHelper.createRotationalVector(0f, 0f, 27.5f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-57.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.45833f, AnimationHelper.createRotationalVector(-42.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 30f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.45833f, AnimationHelper.createRotationalVector(0f, 0f, -27.5f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-57.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.45833f, AnimationHelper.createRotationalVector(-42.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("stones",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final AnimationDefinition THROW_BLOCK = AnimationDefinition.Builder.create(0.83333f)
	.addBoneAnimation("left_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("right_arm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(-96.91f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-100f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.45833f, AnimationHelper.createRotationalVector(-107.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.5f, AnimationHelper.createRotationalVector(-90f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("left_elbow",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.33333f, AnimationHelper.createRotationalVector(-67.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.41667f, AnimationHelper.createRotationalVector(-75f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final AnimationDefinition IDLE = AnimationDefinition.Builder.create(1.125f).looping()
	.addBoneAnimation("stones",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, -1.17f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(1.08333f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
}
