package net.balamah.voiddim.entity.client;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class WerewolfAnimations {
	public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(0f).build();
	public static final AnimationDefinition ATTACK_BITE = AnimationDefinition.Builder.withLength(0.375f)
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("jaw",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.20833f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("upper_mouth",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.125f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.20833f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_shoulder_bicep",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_shoulder_bicep",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.33333f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition ATTACK_HIT = AnimationDefinition.Builder.withLength(0.5834334f)
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("front_paws",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08343333f, KeyframeAnimations.degreeVec(-155f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16766666f, KeyframeAnimations.degreeVec(-85f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.4167667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
	public static final AnimationDefinition WALK = AnimationDefinition.Builder.withLength(0.7083434f).looping()
	.addAnimation("tail",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("back_paws",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.08333f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(30f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.29167f, KeyframeAnimations.degreeVec(-27.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(-37.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.54167f, KeyframeAnimations.degreeVec(-49.95f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.70833f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("body",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.2916767f, KeyframeAnimations.degreeVec(12.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.66667f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_front_paw",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.29167f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(13.5f, 5.9f, 19.14f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.70833f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("right_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.29167f, KeyframeAnimations.degreeVec(2.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.70833f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_front_paw",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.29167f, KeyframeAnimations.degreeVec(-17.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.41667f, KeyframeAnimations.degreeVec(18.26f, -5.19f, -16.74f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.70833f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR)))
	.addAnimation("left_elbow",
		new AnimationChannel(AnimationChannel.Targets.ROTATION,
			new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.16667f, KeyframeAnimations.degreeVec(-25f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.29167f, KeyframeAnimations.degreeVec(-2.5f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR),
			new Keyframe(0.70833f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
				AnimationChannel.Interpolations.LINEAR))).build();
}
