package net.balamah.voiddim.entity.client;

import net.minecraft.client.render.entity.animation.*;

public class WormOfCorruptionAnimations {
	public static final AnimationDefinition IDLE = AnimationDefinition.Builder.create(0f).build();
	public static final AnimationDefinition ATTACK = AnimationDefinition.Builder.create(0.45833f)
	.addBoneAnimation("head",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(0f, 0f, -9f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("head",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("upper",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(27.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_3",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_4",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(0f, 0f, -2f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_4",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_5",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(0f, 0f, -4f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_5",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final AnimationDefinition SHOOT = AnimationDefinition.Builder.create(0.45833f)
	.addBoneAnimation("head",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.16667f, AnimationHelper.createRotationalVector(22.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("upper",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(27.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final AnimationDefinition DIG_UP = AnimationDefinition.Builder.create(0.5f)
	.addBoneAnimation("root",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -50f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("head",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(-92.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(-97.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.375f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("upper",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(25f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("lower",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(25f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.29167f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("miasma",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.08333f, AnimationHelper.createTranslationalVector(0f, 44f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.29167f, AnimationHelper.createTranslationalVector(0f, 50.25f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("worm",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(0f, 51.71f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.29167f, AnimationHelper.createTranslationalVector(0f, 50.25f, 0f),
				Transformation.Interpolations.LINEAR))).build();
	public static final AnimationDefinition DIG_DOWN = AnimationDefinition.Builder.create(0.875f)
	.addBoneAnimation("head",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.08333f, AnimationHelper.createTranslationalVector(0f, -0.75f, 4.25f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("head",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_2",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_3",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.08333f, AnimationHelper.createTranslationalVector(0f, 0f, 0.5f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_3",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_4",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.08333f, AnimationHelper.createTranslationalVector(0f, 0f, 1f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_4",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_5",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.08333f, AnimationHelper.createTranslationalVector(0f, 0f, 2f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("body_5",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.08333f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("worm",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.08333f, AnimationHelper.createTranslationalVector(0f, 39f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.20833f, AnimationHelper.createTranslationalVector(0f, 61f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.66667f, AnimationHelper.createTranslationalVector(0f, -84f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("worm",
		new Transformation(Transformation.Targets.ROTATE,
			new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR),
			new Keyframe(0.375f, AnimationHelper.createRotationalVector(180f, 0f, 0f),
				Transformation.Interpolations.LINEAR)))
	.addBoneAnimation("miasma",
		new Transformation(Transformation.Targets.MOVE_ORIGIN, 
			new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
				Transformation.Interpolations.LINEAR), 
			new Keyframe(0.16667f, AnimationHelper.createTranslationalVector(0f, -24.25f, 0f),
				Transformation.Interpolations.LINEAR))).build();
}
