#!/bin/sh

# $1 :: path to model blockbench class

. ./scripts/functions.sh

[ -z "$1" ] && printParameters && exit 1

cat "$1" | \
	sed 's/extends EntityModel<Entity>/extends EntityModel<RENDER_STATE>/;
	s/public static TexturedModelData getTexturedModelData()/public static LayerDefinition getLayerDefinition()/;
	s/ModelData modelData = new ModelData();/MeshDefinition modelData = new MeshDefinition();/;
	s/ModelPartData /PartDefinition /g;
	s/ModelPartBuilder/CubeListBuilder/g;
	s/\.uv(/.texOffs(/g;
	s/\.cuboid(/.addBox(/g;
	s/new Dilation(/new CubeDeformation(/g;
	s/ModelTransform\.pivot(/PartPose.offset(/g;
	s/ModelTransform\.of(/PartPose.offsetAndRotation(/g;
	s/\.addChild(/.addOrReplaceChild(/g;
	s/return TexturedModelData\.of(modelData, 64, 64);/return LayerDefinition.create(modelData, 64, 64);/;
	/@Override$/d;
	/public void setAngles(/,/^	}/d;
	/public void render(/,/^	}/d'
